name: Build and Publish Docker Image

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - docker-build

env:
  DOCKER_IMAGE: matracey/croc

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build --build-arg tag_name=${{ github.event.client_payload.tag_name }} -t $DOCKER_IMAGE:${{ github.event.client_payload.tag_name || 'latest' }} .

      - name: Push Docker Image
        run: |
          docker push $DOCKER_IMAGE:${{ github.event.client_payload.tag_name || 'latest' }}

      - name: Set Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          repository: $DOCKER_IMAGE
